<?php

namespace GenAI\Dto\Processor;

use GenAI\Attribute\AttributeProcessor;
use GenAI\Attribute\Context;
use GenAI\Dto\Attribute\Dto;

/**
 * Compiles a JSON serialization map for #[Dto] value objects. For each marked
 * class it records its public no-arg getXxx()/isXxx() methods as field => getter,
 * and dumps cache/dto.php:
 *
 *   return array(
 *       'App\\Dto\\UserDTO' => array('id' => 'getId', 'name' => 'getName'),
 *   );
 *
 * The runtime Serializer reads this map to turn a DTO into an array via its
 * getters — no runtime reflection, no hand-written toArray().
 *
 * Build-time only (PHP 8). The dumped file is PHP 5.3-safe.
 */
class DtoProcessor implements AttributeProcessor
{
    /** @var array<string, array> class => (field => getter method) */
    private array $dtos = [];

    public function getAttributeClass(): string
    {
        return Dto::class;
    }

    public function process(object $attribute, \Reflector $target): void
    {
        /** @var \ReflectionClass $target */
        $fields = array();
        foreach ($target->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
            if ($method->isStatic() || $method->getNumberOfRequiredParameters() !== 0) {
                continue;
            }

            $name = $method->getName();
            if (str_starts_with($name, 'get') && strlen($name) > 3) {
                $field = lcfirst(substr($name, 3));   // getId -> id
            } elseif (str_starts_with($name, 'is') && strlen($name) > 2) {
                $field = lcfirst(substr($name, 2));    // isActive -> active
            } else {
                continue;
            }

            $fields[$field] = $name;
        }

        $this->dtos[$target->getName()] = $fields;
    }

    public function compile(Context $context): void
    {
        $source = "<?php\n\n"
            . "namespace Cache;\n\n"
            . "// Generated by GenAI\\Dto\\Processor\\DtoProcessor - do not edit by hand.\n"
            . "// The compiled serializer: new \\Cache\\Dto() is ready to use.\n\n"
            . "class Dto extends \\GenAI\\Dto\\MapSerializer\n"
            . "{\n"
            . "    public function __construct()\n"
            . "    {\n"
            . '        $this->setMap(' . var_export($this->dtos, true) . ");\n"
            . "    }\n"
            . "}\n";

        $path  = $context->output('Dto.php');
        $bytes = @file_put_contents($path, $source);
        if ($bytes === false) {
            throw new \RuntimeException('Could not write DTO map to "' . $path . '".');
        }
    }
}
